# Generated by Django 6.1.1 on 2026-09-24 20:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('porcentaje_avance', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('CUMPLIDA', 'Cumplida'), ('VENCIDA', 'Vencida'), ('OBSERVADA', 'Observada'), ('SUSPENDIDA', 'Suspendida'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=10)),
                ('es_hito', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actividad_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subactividades', to='actividades.actividad')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='proyectos.proyecto')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades_responsables', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='actividades.tipoactividad')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['fecha_fin', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='DependenciaActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FIN_INICIO', 'Fin - Inicio'), ('INICIO_INICIO', 'Inicio - Inicio'), ('FIN_FIN', 'Fin - Fin'), ('INICIO_FIN', 'Inicio - Fin')], default='FIN_INICIO', max_length=20)),
                ('retraso_dias', models.PositiveIntegerField(default=0, verbose_name='Retraso en días')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencias', to='actividades.actividad')),
                ('depende_de', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_dependientes', to='actividades.actividad')),
            ],
            options={
                'verbose_name': 'Dependencia entre actividades',
                'verbose_name_plural': 'Dependencias entre actividades',
                'constraints': [models.UniqueConstraint(fields=('actividad', 'depende_de'), name='dependencia_unica')],
            },
        ),
        migrations.AddConstraint(
            model_name='actividad',
            constraint=models.UniqueConstraint(fields=('proyecto', 'codigo'), name='codigo_unico_por_proyecto'),
        ),
    ]
