# Generated by Django 6.1.1 on 2026-09-24 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEnlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nivel 0')),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría de enlaces',
                'verbose_name_plural': 'Categorías de enlaces',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='GrupoEnlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Nivel 1')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='enlaces.categoriaenlace', verbose_name='Nivel 0')),
            ],
            options={
                'verbose_name': 'Grupo de enlaces',
                'verbose_name_plural': 'Grupos de enlaces',
                'ordering': ['orden', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='EnlaceInteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True)),
                ('url', models.URLField(verbose_name='Enlace')),
                ('observaciones', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enlaces', to='enlaces.grupoenlace', verbose_name='Nivel 1')),
            ],
            options={
                'verbose_name': 'Enlace de interés',
                'verbose_name_plural': 'Enlaces de interés',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
