# Generated by Django 6.1.1 on 2026-09-24 20:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvanceActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_corte', models.DateField()),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('comentario', models.TextField(blank=True)),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_avances', to='actividades.actividad')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avances_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avance de actividad',
                'verbose_name_plural': 'Avances de actividades',
                'ordering': ['-fecha_corte', '-registrado_en'],
            },
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('GENERAL', 'General'), ('RETRASO', 'Retraso'), ('RIESGO', 'Riesgo'), ('DOCUMENTAL', 'Documental'), ('TECNICA', 'Técnica')], default='GENERAL', max_length=20)),
                ('texto', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('atendida', models.BooleanField(default=False)),
                ('fecha_atencion', models.DateField(blank=True, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones_registradas', to='actividades.actividad')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
