# Generated by Django 6.1.1 on 2026-09-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='baselegal',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='actividad',
            name='control',
            field=models.CharField(choices=[('Contratista', 'Contratista'), ('Contratista + Supervisor + DPDRH', 'Contratista + Supervisor + DPDRH'), ('Contratista → ANA', 'Contratista → ANA'), ('Contratista → Supervisor', 'Contratista → Supervisor'), ('DPDRH', 'DPDRH'), ('DPDRH / ANA → Contratista', 'DPDRH / ANA → Contratista'), ('DPDRH → Contratista', 'DPDRH → Contratista'), ('DPDRH/ANA → Supervisor', 'DPDRH/ANA → Supervisor'), ('Oficina de Administración (ANA)', 'Oficina de Administración (ANA)'), ('Supervisor', 'Supervisor'), ('Supervisor → DPDRH', 'Supervisor → DPDRH')], default='Contratista', max_length=50),
        ),
    ]
