# Generated by Django 6.1.1 on 2026-09-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0002_actividad_baselegal_actividad_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
